BiggerPockets/patterns

rails/crud-actions-only.md
proposes a new rule that we restrict the actions and methods in a controller to those that handle the four core RESTful actions - create, read, update, and delete.
=> CRUD actions only in controllers

ruby/.rubocop.yml
=> Add production environment

rspec/dont-sleep.md
Inspired by recent flaky test encounters.
More info:
https://web.archive.org/web/20131115011500/http://engineering.nulogy.com/posts/sleep-is-for-the-weak/
=> Add guide on not sleeping

ruby/dont-lock-gems.md
Follows discussion here:
https://github.com/BiggerPockets/biggerpockets/pull/8579/files#r336658166
=> Dont lock gems

rails/query-object-over-queries-on-models-or-controllers.md
https://github.com/BiggerPockets/biggerpockets/pull/8603
=> query object pattern over queries for object in model or controller

rails/app-and-lib.md
Closes https://github.com/BiggerPockets/patterns/issues/30
=> Add guide on app vs lib

values.html
I exported our Google Doc containing these as HTML, then ran the output through htmlcleaner.com and this is the result!
=> Add Values

_patterns/path-hyphens.md
Paths should be hyphenated.
@EddM perhaps you can expand on why this is?
=> Paths have hyphens

_patterns/spec-randomness.md, _patterns/use-real-world-data.md
Add a pattern regarding random spec data.
=> Randomness in specs

_patterns/avoid-environment-conditionals.md
Partly addresses https://github.com/BiggerPockets/patterns/issues/25
Follows https://github.com/BiggerPockets/biggerpockets/pull/9703#discussion_r399142302
=> Add guide on avoiding env conditionals

ruby/.rubocop.yml
As per https://github.com/BiggerPockets/biggerpockets/pull/9792#discussion_r404706007
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ClassAndModuleChildren
(I also added review to allowed environments)
=> Nested class definitions

_patterns/code-review.md, _patterns/creating-a-pr.md
Closes https://github.com/BiggerPockets/patterns/issues/40
=> Add PR guide

_patterns/dont-use-subjective-or-time-based-naming.md
I think this is a good one. However I'm not sure my `Good` example makes the most sense in terms of the naming I have chosen? LMKWYT
=> Avoid subjective and time based nomenclature

_patterns/spec-randomness.md
This should also trigger a redeploy of the BiggerPockets Patterns Jekyll
app once the master branch has been renamed to main.
=> This updates a FactoryBot URL to refer to the correct branch

_scheduled_jobs.md
Adds guidance on how to schedule jobs
=> Scheduled jobs

_patterns/validate-correctly-on-the-edge.md
Validate data on the edge of the app.
So that we don't get bad data in the database.
=> Validate data on the edge of the app using `dry-validation`

_patterns/prefer-rescuing-using-active-support-error-handler.md
Jira ticket: BIG-8954
Detail error handling from Rails 7
To help folk decide how to use it and provide some basic docs around usage.
=> Handle errors using Rails.error

ruby/.rubocop.yml
RuboCop Performance is an [official extension](https://docs.rubocop.org/rubocop/extensions.html#official-extensions) of RuboCop focused on performance optimization analysis. It applies suggestions that would make your code more performant. The cops it adds are [defined here](https://docs.rubocop.org/rubocop-performance/cops.html).
Some illustrative examples of the types of suggestions it adds are:
[Performance/DeletePrefix](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancedeleteprefix)
```ruby
str.gsub(/\Aprefix/, '')
str.gsub!(/\Aprefix/, '')
str.sub(/\Aprefix/, '')
str.sub!(/\Aprefix/, '')
str.delete_prefix('prefix')
str.delete_prefix!('prefix')
```
[Performance/FlatMap](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceflatmap) …
=> Add RuboCop Performance

_patterns/creating-a-pr.md
Revise the publicly facing pull request documentation.
It's still not clear what's expected as a reviewer from a PR
Flesh out the public facing documentation.
Once this is approved and merged, we'll deprecate all internal docs for PRs and point to this one.
=> Improve PR process

ruby/.rubocop.yml
Enforce https://github.com/BiggerPockets/patterns/pull/171
=> Enable Trailing Comma with consistent_comma style

_patterns/crud-actions-only.md
Generally it's a good practice to not have too many actions in your controllers, but I want to carve out an exception for this for what are pretty common patterns.
=> Change CRUD restrict to prefer and explain why

_patterns/use-null-object-pattern-to-implement-guest-users.md
A pattern to demonstrate the benefits by having a first class `GuestSocialUser` model to deal with guest users.
Because of the current complexity and error prone code.
=> Use null object pattern to simplify dealing with guest users
