- ruby/ampersand-and-nils.md
proposes a new rule saying we shouldn't use the safe navigation operator (`&.`) unless the receiver could legitimately be `nil`
(if anyone has a better example to add for this particular rule, I'm all ears)
> Don't use safe navigation operator on unexpected nils

- ruby/.rubocop.yml
This PR extracts our Rubocop config to the patterns repo.
We can then pull it back into the project as required with the rubocop `inherit_from` setting.
https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md#configuration
> Add Rubocop config

- js/avoid-element-selection-in-loops.md
- js/detach-dom-elements.md
- js/use-for-not-each.md
After determining that front end performance (in the case of `/goals`) improved linearly with removal of files in `app/assets/javascripts` I have written a few initial guidelines/rules as how to hopefully not completely kill performance with JQuery.
Ideally we'd probably remove JQuery all together at some point 😏
> [BIG-4421]/Some-js-guidelines

- ruby/.rubocop.yml
Closes https://github.com/BiggerPockets/biggerpockets/issues/8687
Solves the following types of warnings:
```
Warning: unrecognized cop ActionFilter found in .rubocop-https---raw-githubusercontent-com-BiggerPockets-patterns-master-ruby--rubocop-yml
```
> Require rubocop-rails

- ruby/.rubocop.yml
increment! persists to the database and skips model validations. Normally this isn't a problem and we don't need warning about this.
> Allow increment!

- ruby/.rubocop.yml
Fixes:
Error: The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-BiggerPockets-patterns-master-ruby--rubocop-yml, please update it)
The `Layout/IndentFirstHashElement` cop has been renamed to `Layout/FirstHashElementIndentation`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-BiggerPockets-patterns-master-ruby--rubocop-yml, please update it)
The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-BiggerPockets-patterns-master-ruby--rubocop-yml, please update it)
obsolete parameter NamePrefixBlacklist (for Naming/PredicateName) found in …
> Update Rubocop config

- rails/use-active-job.md
Closes https://github.com/BiggerPockets/patterns/issues/23
Proposes we standardise on [activejob](https://edgeguides.rubyonrails.org/active_job_basics.html) rather than sidekiq-specific workers.
> Add guide on using activejob

- _patterns/code-review.md
- practices/index.md
This PR gives us a starting point to think about code review in our team.
I hope we can expand it as time goes on.
It's based on https://github.com/thoughtbot/guides/tree/master/code-review but I tried to adapt that to meet our needs and focus less on the things we don't have a problem with (in my opinion).
Feedback and discussion welcome here!
> Add guide for code review

- ruby/.rubocop.yml
I've made the following improvements to our Rubocop config:
- Closes https://github.com/BiggerPockets/patterns/issues/38
- Every cop is now [namespaced](https://github.com/rubocop-hq/rubocop/issues/1097)
- Cops are now sorted alphabetically and grouped by their namespace
- I removed StringLiteralsInInterpolation due to the following outdated comment: "# StringLiteralsInInterpolation disabled because of a bug in rubocop https://github.com/bbatsov/rubocop/issues/1415"
There should be no actual material changes to our config here.
Sorry the diff is pretty useless here.
> Refactor Rubocop config

- ruby/.rubocop.yml
Leaving a trailing comma on a multiline array or hash literal makes for a cleaner git diff. It also makes things consistent with our ESLint rules:
```rb
a = { foo: 1, bar: 2, }
a = { foo: 1, bar: 2 }
a = {
foo: 1, bar: 2,
qux: 3,
}
a = {
foo: 1, bar: 2, qux: 3,
}
a = {
foo: 1,
bar: 2,
}
```
```rb
a = [1, 2,]
a = [1, 2]
a = [
1, 2,
3,
]
a = [
1, 2, 3,
]
a = [
1,
2,
]
```
> Enforce trailing commas in hash and array literals

- ruby/.rubocop.yml
The majority of our codebase uses brackets rather than %i or %w to define array literals.
This change to our Rubocop config formalizes that.
https://rubocop.readthedocs.io/en/latest/cops_style/#stylewordarray
```rb
["foo", "bar", "baz"]
%w[foo bar baz]
```
https://rubocop.readthedocs.io/en/latest/cops_style/#stylesymbolarray
```rb
[:foo, :bar, :baz]
%i[foo bar baz]
```
> Brackets style for arrays of symbols and words

- ruby/.rubocop.yml
Closes https://github.com/BiggerPockets/patterns/issues/60
This change enforces this rule:
```rb
def expensive_method
@expensive_method ||= computation
end
def expensive_method
@_expensive_method ||= computation
end
```
> Enforce memoization instance variables begin with an underscore

- ruby/.rubocop.yml
This PR enables new cops automatically.
It also enables TrailingCommaInArguments for multiline arguments:
```
foo(bar)
foo(bar, baz)
foo(
bar,
baz,
)
foo(bar,)
foo(bar, baz,)
foo(
bar,
baz
)
```
> Enable new cops and make multiline method arguments have a trailing comma

- ruby/.rubocop.yml
Fixes the following warning:
```
Warning: Rails/SkipsModelValidations does not support Whitelist parameter.
Supported parameters are:
- Enabled
- ForbiddenMethods
- AllowedMethods
```
> Address Rubocop warning

- ruby/.rubocop.yml
Fixes a warning I noticed locally.
> Rename ExcludedMethods to IgnoredMethods

- ruby/.rubocop.yml
Fixes the warning as described at https://github.com/github/rubocop-github/issues/54
> Move LineLength to Metrics namespace

- ruby/.rubocop.yml
People who have their local environment set to autocorrect with Rubocop (the `-a` flag) are pushing commits that have broken autocorrects ([example](https://github.com/BiggerPockets/biggerpockets/pull/12940/commits/2e16e0ffedcb01c7fd266dde22094b7311a9e9cc#diff-69cfeb91ed2e903fff955435f51f2df6215e86ca76b96e47022dbf0f8f93480cR39))
This updates our Rubocop config so that these (obviously broken) autocorrect procedures do not run
> Disable autocorrect for trailing comma cops

- ruby/.rubocop.yml
Since we're now using RSpec tags specifically `flaky` and `driver: :legacy_headless_chrome` this check is being flagged / failed more often:
I propose we simply exclude this rule from all files within `spec/**/*`
> Don't limit line length within test suite

- ruby/.rubocop.yml
This nanny has a ton of false positives, we're now up to 40 ignores. Let's just go ahead and disable this and rely on code review to address function complexity issues.
> Disable Metrics/AbcSize

- ruby/.rubocop.yml
Since the file `db/data_schema.rb` is automatically generated by [data-migrate](https://github.com/ilyakatz/data-migrate) I think it makes sense to exclude it from RoboCop. We already do this for `db/schema.rb`.
> Exclude db/data_schema.rb 

- ruby/.rubocop.yml
Any method named `find_by_*` is triggering `Rails/DynamicFindBy` errors. You can see an example [here](https://github.com/BiggerPockets/biggerpockets/pull/14839/files).
ActiveRecord used to provide dynamic find_by but it was [removed from Rails since Rails 5](https://github.com/rails/activerecord-deprecated_finders/blob/master/README.md). Since we're not using the gem `activerecord-deprecated_finders` and we're running on Rails `6.1.x` this cop offers no value and will only trigger false positives.
> Disable Rails/DynamicFindBy cop

- _patterns/dont-sleep.md
These headings must include some invisible characters because Markdown wasn't identifying them as headings.
> Fix headings in pattern

- _patterns/path-hyphens.md
It's not really clear, but I think that this was originally meant to say that underscores could not be used in hostnames. Hyphens can be used in hostnames.
> Update that hyphens are allowed in hostnames

- ruby/.rubocop.yml
Rails is going to keep adding these. Best to just ignore it.
> Ignore Rails' default blank lines at block start

- _patterns/two-step-deploy.md
[JIRA TICKET
](https://biggerpockets.atlassian.net/jira/software/c/projects/BIG/boards/10?modal=detail&selectedIssue=BIG-8212&assignee=5a3450a1e8d80e393b434cbf)
- Add a two-step deployment process while dropping a column on a table.
- We don't want the application to crash when we deploy a pull request that has changes on dropping a column.
- Add documentation on how we can safely deploy the PR involving the changes on dropping a column in the 2-step deploy process.
> [BIG-8212] Add two step deploy pattern

- ruby/.rubocop.yml
Update Rubocop rules to force specifying hash values rather than omitting them with the new syntax in Ruby 3.1.
Our PRs are being littered with this warning:
This is because latest version of Ruby (3.1+) allow omitting values from hashes. So Rubocop use this rule:
```ruby
{foo: foo, bar: bar}
{foo:, bar:}
```
This forces terseness onto the author using an unfamiliar syntax. Personally, I'm not a fan of this syntax as it makes it less clear what's going on.
For now, for consistency, force us to use the old syntax.
Add `EnforcedShorthandSyntax: never` option so it forces us to be consistent and use the original style syntax.
If we want to add in the new style at some point in the future, we can change this to `always`.
Updated my local `.rubocop.yml` file to:
```yaml
inherit_from: …
```
> [no-ticket] Remove noisy `Style/HashSyntax` Rubocop violations

- ruby/.rubocop.yml
I want to be able to privatize a method whilst keeping it in the context of related code. With Ruby 3, that's now an option, but we would need to disable the cop.
This change allows the following syntax form:
```ruby
private def super_secret_function
end
```
> Allow inline method scope declarations

- ruby/.rubocop.yml
Ref https://github.com/rubocop/rubocop/pull/10829
```shell
Warning: obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in .rubocop-https---raw-githubusercontent-com-BiggerPockets-patterns-master-ruby--rubocop-yml `IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.
```
> Rename obsolete IgnoredMethods to AllowedMethods

- ruby/.rubocop.yml
We have `config.active_record.belongs_to_required_by_default` set to `false`, so we need to explicitly set that validation when needed.
https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/RedundantPresenceValidationOnBelongsTo
> Since Rails 5.0 the default for `belongs_to` is `optional: false` unless `config.active_record.belongs_to_required_by_default` is explicitly set to `false`. The presence validator is added automatically, and explicit presence validation is redundant.
> Disable Rails/RedundantPresenceValidationOnBelongsTo rubocop rule

- ruby/.rubocop.yml
Not sure why, but reviewdog or rubocop is not properly excluding this from cops via the AllCops directive.
> Don't consider line length in schema.rb

- ruby/.rubocop.yml
This file is automatically managed and should not be scanned by rubocop.
These cops should be ignored via the `AllCops` directive, but they're not.
> Exclude db/data_schema.rb from magic string cop

- ruby/.rubocop.yml
We have been utilizing [`#update_counters`](https://api.rubyonrails.org/classes/ActiveRecord/CounterCache/ClassMethods.html#method-i-update_counters) in ActiveRecord to avoid race conditions, as explained in this article: https://www.honeybadger.io/blog/activerecord-update-counters-race-conditions/
However, every time we use this method, it attracts unwanted attention from the authorities, and we must manually evade them.
It would be logical to exclude [`#update_counters`](https://api.rubyonrails.org/classes/ActiveRecord/CounterCache/ClassMethods.html#method-i-update_counters) from [Rails/SkipsModelValidations](https://www.rubydoc.info/gems/rubocop/0.51.0/RuboCop/Cop/Rails/SkipsModelValidations). This is because when using it, it is likely to be either for updating a counter cache or to …
> RuboCop allow `update_counters`

- _patterns/use-feature-repo-for-feature-access-checks.md
The platform team have recently added a `Features::FeatureRepo` that contains all feature definitions.
Let's use this for any features we need to define in future.
So that we can have consistency in how we define features and be able to see them all in one place.
> Describe features at a high level rather than querying the user model directly

- _patterns/prefer-shortened-namespaces.md
- To make the codebase more readable
- To make the codebase more consistent
- To address some of the very long namespaces
> Prefer shortened namespaces

- _patterns/use-case-insensitive-columns.md
Instead of using lower() on every query where downcase is necessary, we can use citext extension for which downcasing will not be necessary.
No Old data updates, But for new columns coming up we will implement this.
> Add Citext for case insensitive columns

- ruby/.rubocop.yml
This cop checks for the use of methods which skip validations which are listed in [guides.rubyonrails.org/active_record_validations.html#skipping-validations](http://guides.rubyonrails.org/active_record_validations.html#skipping-validations)
There are many situations where we legitimately want to skip validations. 
For example: 
- https://github.com/BiggerPockets/biggerpockets/pull/18828
- https://github.com/BiggerPockets/biggerpockets/blob/f1d72c6ab7f7b98469c5b0bc6ecb1c4bc663131b/lib/migrations/backfill_insecure_password_to_social_users.rb
- https://github.com/BiggerPockets/biggerpockets/blob/5ef53618a03421e987f02acc9483632b01fb8d5f/app/controllers/api/v1/notifications_controller.rb#L37-L39
Currently, in the codebase, we've written `# rubocop:disable Rails/SkipsModelValidations` 65 …
> Disable Rails/SkipsModelValidations

- ruby/.rubocop.yml
This cops checks for the use of output calls like puts and print
```
puts 'A debug message'
pp 'A debug message'
print 'A debug message'
[Rails](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails).logger.debug 'A debug message'
```
It's important to note that there are situations where we legitimately want to print to Stdout. For instance:
- https://github.com/BiggerPockets/biggerpockets/pull/18701#pullrequestreview-1584751210
- https://github.com/BiggerPockets/biggerpockets/blob/beccaf3f2b75459f02793355ef81ac2d47d61be4/lib/generators/widget/widget_generator.rb#L13
We should keep in mind that people might blindly follow the cop's advice without considering circumstantial nuances, which can sometimes cause more hassle than it's worth.
> Disable Rails/Output

- _patterns/best_practices_on_writing_a_script.md
- _patterns/running-data-migration.md
Followup keynotes: 
- Down the road, once we have this process established, we can have a generator script to automatically generate the scaffold files for the data migration.
- Over time, we will have a huge list of migration scripts, and we will need to have some sort of scheduled cleanup process to remove legacy migration scripts
> Add a patttern for running data migration

- ruby/.rubocop.yml
RuboCop RSpec is an [official extension](https://docs.rubocop.org/rubocop/extensions.html#official-extensions) of RuboCop focused on enforcing the guidelines and best practices outlined in the community [RSpec style guide](https://rspec.rubystyle.guide/). 
It contains [RSpec/Capybara](https://docs.rubocop.org/rubocop-rspec/cops_rspec_capybara.html), which, amongst other things, offers suggestions on how to interact with Capybara in a manner which avoids accidentally writing flaky specs.
Some illustrative examples of the types of suggestions it adds are:
[RSpec/Capybara/CurrentPathExpectation](https://docs.rubocop.org/rubocop-rspec/cops_rspec_capybara.html#rspeccapybaracurrentpathexpectation)
```ruby
expect(current_path).to eq('/callback')
expect(page).to have_current_path('/callback') …
```
> Add RuboCop RSpec/Capybara

- ruby/.rubocop.yml
This addition was inadvertently included via https://github.com/BiggerPockets/biggerpockets/pull/20411 as it is a transient dependency of https://github.com/rubocop/rubocop-rspec.
I will proceed with merging without awaiting the customary six approvals, as this change was an unintentional error and not in line with the team's agreement.
I apologize if this decision is deemed inappropriate, but I believe it's necessary to prevent engineers from addressing non-existent Rubocop issues.
> Disable RuboCop FactoryBot checks

- ruby/.rubocop.yml
I suggest we remove enforcing trailing comma due to the following reasons:
- When trailing comma is missed, fixing it prolongs the pull request iteration process, as developers must wait for the CI to pass again after addressing this issue.
- Trailing comma was not originally enforced, so additional modifications are often necessary to satisfy rubocop introducing unnecessary changes.
- Ruby prohibits the use of a comma at the end of attributes spread across multiple lines, which creates inconsistencies like this:
> Remove trailing comma rule

- _patterns/prefer_faraday_as_http_client.md
Although less fun, when using an http client in the app, use Faraday when possible.
> Add preferred http client

- ruby/.rubocop.yml
We removed the trailing comma rule here:https://github.com/BiggerPockets/patterns/pull/188
Removing it completely applies the rule to remove the comma in existing code.
> Don't force removal of the commas

- ruby/.rubocop.yml
Fix the TrailingComma rules.
When disabling a rubocop rule add `Enabled: false`.
> Don't force removal of the commas - fix the rule
